# Generated by Django 4.2.5 on 2024-03-22 16:55

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('skill1', models.CharField(blank=True, max_length=100)),
                ('skillsize1', models.CharField(blank=True, max_length=3)),
                ('skill2', models.CharField(blank=True, max_length=100)),
                ('skillsize2', models.CharField(blank=True, max_length=3)),
                ('skill3', models.CharField(blank=True, max_length=100)),
                ('skillsize3', models.CharField(blank=True, max_length=3)),
                ('skill4', models.CharField(blank=True, max_length=100)),
                ('skillsize4', models.CharField(blank=True, max_length=3)),
                ('skill5', models.CharField(blank=True, max_length=100)),
                ('skillsize5', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where_home', models.CharField(blank=True, max_length=2)),
                ('where_projects', models.CharField(blank=True, max_length=2)),
                ('where_university', models.CharField(blank=True, max_length=2)),
                ('Where_carusel', models.CharField(blank=True, max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('titleHome', models.CharField(blank=True, max_length=200)),
                ('summary', models.CharField(blank=True, max_length=250)),
                ('body', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('photo_carusel', models.ImageField(blank=True, upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
