# Generated by Django 4.2.5 on 2024-03-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='skill1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='skill2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='skill3',
        ),
        migrations.RemoveField(
            model_name='about',
            name='skill4',
        ),
        migrations.RemoveField(
            model_name='about',
            name='skill5',
        ),
        migrations.RemoveField(
            model_name='about',
            name='skillsize1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='skillsize2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='skillsize3',
        ),
        migrations.RemoveField(
            model_name='about',
            name='skillsize4',
        ),
        migrations.RemoveField(
            model_name='about',
            name='skillsize5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
