# Generated by Django 4.2.5 on 2024-03-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_remove_about_skill1_remove_about_skill2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Where_carusel',
            new_name='where_carusel',
        ),
    ]
