# Generated by Django 5.0 on 2023-12-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_post_author_remove_post_date_post_oq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kumush',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='photo1k',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo2k',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo3k',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo4k',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
