# Generated by Django 5.0 on 2023-12-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_kumush_post_photo1k_post_photo2k_post_photo3k_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sariq',
            new_name='tilla',
        ),
    ]
