# Generated by Django 5.0 on 2023-12-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sharhsoni',
            new_name='mahsulot_soni',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='ism',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='linkphoto',
            new_name='number_product',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='linktitle',
            new_name='tel_number',
        ),
        migrations.RemoveField(
            model_name='post',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='telnumber',
        ),
    ]
