# Generated by Django 4.2.4 on 2023-09-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='skill1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='skill2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='skill3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='skill4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='skill5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='skillsize1',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='about',
            name='skillsize2',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='about',
            name='skillsize3',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='about',
            name='skillsize4',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='about',
            name='skillsize6',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
