# Generated by Django 4.2.4 on 2023-09-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_about_skill1_about_skill2_about_skill3_about_skill4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='skillsize6',
            new_name='skillsize5',
        ),
    ]
