# Generated by Django 4.2.5 on 2023-09-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_rename_skillsize6_about_skillsize5'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titleHome',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
