# Generated by Django 3.1.14 on 2023-12-02 17:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turlari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=200)),
                ('soni', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='boshsahifada',
            new_name='hometitle',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='qisqachainfo',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tuliqinfo',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='photo4',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
