# Generated by Django 5.0 on 2023-12-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_narxchegara'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='forhome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='maylike',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
