# Generated by Django 5.0 on 2024-03-01 18:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_upload_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='narx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='narxchegara',
            name='dan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='narxchegara',
            name='gacha',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
