# Generated by Django 3.1.14 on 2023-12-01 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('boshsahifada', models.CharField(blank=True, max_length=200)),
                ('qisqachainfo', models.CharField(blank=True, max_length=250)),
                ('tuliqinfo', models.TextField(blank=True)),
                ('photo1', models.ImageField(blank=True, upload_to='images/')),
                ('photo2', models.ImageField(blank=True, upload_to='images/')),
                ('photo3', models.ImageField(blank=True, upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
