# Generated by Django 3.1.14 on 2023-12-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20231202_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turlari',
            old_name='turi',
            new_name='title',
        ),
    ]
