# Generated by Django 5.0 on 2023-12-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_rename_sariq_post_tilla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo1k',
            new_name='photo5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='kumush',
        ),
        migrations.RemoveField(
            model_name='post',
            name='oq',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo1o',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo1q',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo1s',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo2k',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo2o',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo2q',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo2s',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo3k',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo3o',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo3q',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo3s',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo4k',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo4o',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo4q',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo4s',
        ),
        migrations.RemoveField(
            model_name='post',
            name='qora',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tilla',
        ),
    ]
