# Generated by Django 5.0 on 2023-12-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_rename_sharhsoni_post_mahsulot_soni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narxchegara',
            name='dan',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='narxchegara',
            name='gacha',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='narxchegara',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='hometitle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='mahsulot_soni',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='narxi2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='turi',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='turlari',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
